name: End-to-End Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs: 
  e2e:
    container:
      image: ghcr.io/cargo-lambda/cargo-lambda:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
 
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip postgresql-client
          apt-get install -y python3-dotenv python3-psycopg2 python3-jwt
          

      - name: Run Migrations
        run: |
          (find migrations -type f -name "up.sql" ! -path "*/00000000000000_diesel_initial_setup/*" | sort | xargs cat; cat tests/sample_data.sql) > ./all_up.sql
          PGPASSWORD=postgres psql -h postgres -U postgres -f all_up.sql
      
      - name: Start and Run Tests
        env: 
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
        run: |
          cargo lambda watch -a 0.0.0.0 &
          sleep 5
          python3 tests/init.py

